FROM kong/kong-gateway:2.7.0.0-alpine
# FROM kong/kong-gateway:2.5.1.2-alpine

USER root

#COPY license.json /etc/kong/license.json

ADD https://raw.githubusercontent.com/eficode/wait-for/v2.2.1/wait-for /usr/local/bin/wait-for
RUN chmod 755 /usr/local/bin/wait-for

RUN luarocks install kong-plugin-ping-auth
ENV KONG_PLUGINS=bundled,ping-auth

ENV KONG_PROXY_LISTEN="0.0.0.0:8443 ssl reuseport backlog=16384"
ENV KONG_LUA_SSL_TRUSTED_CERTIFICATE=system
ENV KONG_LUA_SSL_VERIFY_DEPTH=3

#COPY kong.yml /usr/local/kong/conf/kong.yml
#ENV KONG_DECLARATIVE_CONFIG=/usr/local/kong/conf/kong.yml
#ENV KONG_DATABASE=off

