FROM kong/kong-gateway:3.4.1.1-ubuntu

USER root

#COPY license.json /etc/kong/license.json

RUN apt-get update && \
    apt-get install -y netcat unzip curl git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ADD https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for /usr/local/bin/wait-for
RUN chmod 755 /usr/local/bin/wait-for

RUN curl -LO https://luarocks.org/manifests/pingidentity/kong-plugin-ping-auth-1.2.0-1.rockspec
RUN luarocks install kong-plugin-ping-auth-1.2.0-1.rockspec

ENV KONG_PLUGINS=bundled,ping-auth

ENV KONG_PROXY_LISTEN="0.0.0.0:8443 ssl reuseport backlog=16384"
ENV KONG_LUA_SSL_TRUSTED_CERTIFICATE=system
ENV KONG_LUA_SSL_VERIFY_DEPTH=3

#COPY kong.yml /usr/local/kong/conf/kong.yml
#ENV KONG_DECLARATIVE_CONFIG=/usr/local/kong/conf/kong.yml
#ENV KONG_DATABASE=off

